### ISSUE TITLE
getting started 

### ISSUE THREAD

**Issue by ataut** [motiondescriptors/modosc#2]
hi Federico,
I wanted to get started with mo.myo and tried to make the simplest patch to verify it's working. I receive the OSC packets but they are all zeros. Any ideas?
AT

[myomodoscmaxpat.maxpat.zip](https://github.com/motiondescriptors/modosc/files/4432452/myomodoscmaxpat.maxpat.zip)

**Comment by ataut** [comment]
Interestingly this very data seems to be getting to my sequencer... 
<img width="1083" alt="Screenshot 2020-04-04 at 21 44 25" src="https://user-images.githubusercontent.com/32303621/78460989-84f88f00-76bd-11ea-981d-fb56ffcc6241.png">

**Comment by federicoVisi** [comment]
Hi Atau,
I had a look at your patch, the data is correctly sent to port 9996 (which might explain what you got in Ossia?) but the problem was with parsing it using the [OpenSoundControl] object. I have rebuilt your patch using odot objects and now it seems to be working fine, check it out. 
Cheers,
F

[myomodoscmaxpat_FV.maxpat.zip](https://github.com/motiondescriptors/modosc/files/4437244/myomodoscmaxpat_FV.maxpat.zip)
